# Generated by Django 3.0 on 2021-08-13 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestas',
            name='respuesta_correcta',
        ),
        migrations.AddField(
            model_name='preguntas',
            name='respuesta_correcta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mi_respuesta', to='partida.Respuestas'),
        ),
    ]
