# Generated by Django 3.0 on 2021-08-14 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0002_auto_20210813_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta_Incorrecta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_incorrecta', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='preguntas',
            name='respuesta_erronea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mi_respuesta_inc', to='partida.Respuesta_Incorrecta'),
        ),
    ]
