# Generated by Django 3.0 on 2021-08-21 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partida', '0002_auto_20210821_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='pregunta_contestada',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PreguntaContestada',
        ),
    ]
