# Generated by Django 3.0 on 2021-08-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0003_auto_20210821_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='pregunta_contestada',
        ),
    ]
