# Generated by Django 3.0 on 2021-08-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0004_remove_pregunta_pregunta_contestada'),
        ('usuarios', '0002_usuario_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pregunta_contestada',
            field=models.ManyToManyField(to='partida.Pregunta'),
        ),
    ]
